---
- name: Install vim (Ubuntu)
  become: true
  apt:
    name: vim
    state: present
  when:
    - ansible_facts['distribution'] == "Ubuntu"

- name: Install vim (MacOSX)
  homebrew:
    name: vim
    state: present
  when:
    - ansible_facts['distribution'] == "MacOSX"

- name: Create autoload directories
  become: false
  file:
    path: "{{ local_user_homedir }}/.vim/autoload"
    state: directory
    recurse: yes

- name: Create bundle directories
  become: false
  file:
    path: "{{ local_user_homedir }}/.vim/bundle"
    state: directory
    recurse: yes

- name: Install pathogen
  become: false
  copy:
    content: "{{ lookup('url', 'https://raw.githubusercontent.com/tpope/vim-pathogen/master/autoload/pathogen.vim', split_lines=False) }}"
    dest: "{{ local_user_homedir }}/.vim/autoload/pathogen.vim"

